describe('nop commerce', () => {

  it('Test Cases', () => {
    cy.visit('https://demo.nopcommerce.com/')
    cy.contains('a', 'My account').click()
    cy.contains('button', 'Register').click()
    cy.get('#FirstName').type('Bilal')
    cy.get('#LastName').type('Nadeem')
    cy.get('#Email').type('bilalnadeem000@gmail.com')
    cy.get('#Password').type('bilal2468')
    cy.get('#ConfirmPassword').type('bilal2468')
    cy.get('#register-button').click()
    cy.contains('a','Continue').click()
    cy.contains('a','Log in').click()
    cy.get('.email').type('bilalnadeem000@gmail.com')
    cy.get('#Password').type('bilal2468')
    cy.contains('button', 'Log in').click()
    cy.contains('button', 'Save').click()
    cy.get('.header-logo').click()
    cy.get('[placeholder="Search store"]').type('MacBook{enter}')
    cy.go('back')
    cy.get('[data-productid="4"]').click()
    cy.get('.product-review-links').children().eq(0).click()
    cy.go('back')
    cy.contains('button', 'Add to wishlist').click()
    cy.get('#product_enteredQuantity_4').clear().type('4')
    cy.wait(5000)
    cy.get('#add-to-cart-button-4').click()
    cy.wait(7000)
    cy.contains('button', 'Email a friend').click()
    cy.get('.friend-email').type('bilal.nadeem@devsinc.com')
    cy.get('#PersonalMessage').type('It is very good product')
    cy.contains('button', 'Send email').click()
    cy.go('back')
    cy.go('back')
    cy.contains('a', 'Add your review').click()
    cy.get('#AddProductReview_Title').type("Good Product")
    cy.get('#AddProductReview_ReviewText').type('It is very good product')
    cy.get('#addproductrating_4').click()
    cy.contains('button', 'Submit review').click()
    cy.get('.wishlist-label').click()
    cy.get('.cart-label').click()
    cy.get('.qty-input').clear().type('5')
    cy.contains('button', 'Update shopping cart').click()
    cy.wait(5000)
    cy.contains('button', 'Continue shopping').click()
    cy.get('.header-logo').click()
    cy.contains('a', ' Digital downloads').click()
    cy.get('[data-viewmode="list"]').click()
    cy.contains('a', 'If You Wait (donation)').click()
    cy.contains('a', 'Blog').click()
    cy.contains('a', 'Contact us').click()
    cy.get('#Enquiry').type('What are your processes?')
    cy.contains('button', 'Submit').click()
    cy.get('.header-logo').click()
    cy.get('#pollanswers-2').click()
    cy.contains('button', 'Vote').click()
    cy.contains('a', 'Addresses').click()
    cy.contains('button', 'Add new').click()
    cy.get('#Address_FirstName').type('Bilal')
    cy.get('#Address_LastName').type('Nadeem')
    cy.get('#Address_Email').type('bilalnadeem102@gmail.com')
    cy.get('#Address_City').type('Lahore')
    cy.get('#Address_Address1').type('hello world')
    cy.get('#Address_ZipPostalCode').type('77886')
    cy.get('#Address_PhoneNumber').type('99999999999')
    cy.get('#Address_CountryId').select('Pakistan').should('have.value', '150')
    cy.contains('button', 'Save').click()
    cy.contains('a', 'Log out').click()
  })
})